### ISSUE TITLE
Will this module be compatible with v.3.x?

### ISSUE THREAD

**Issue by janekska** [kulesa/redmine_better_gantt_chart#123]
Hi,

Are there any plans to make this module compatible with Redmine 3.x?

brgds
Janeks

**Comment by sysgloo** [comment]
I have a similar question!

**Comment by isabelacristinaterra** [comment]
I have this similar question too!

**Comment by BRUTEF0RCE** [comment]
+1

**Comment by spacekookie** [comment]
What are currently the issues with the plugin under 3.x?

**Comment by cognitus** [comment]
another dead proyect?

**Comment by spacekookie** [comment]
The way that it looks it was just added into redmine a few years ago.

**Comment by archonwang** [comment]
+1 
at present not support redmine 3.X for rails version is low...

loading error:

> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': cannot load such file -- active_support/basic_object (LoadError)
>         from /opt/redmine/plugins/redmine_better_gantt_chart/lib/redmine_better_gantt_chart/active_record/callback_extensions_for_rails3.rb:1:in `<top (required)>'

**Comment by jancybsec** [comment]
The 0.9 release works on Redmine 3.3 if you make the following edits:

- add the activerecord-deprecated_finders gem to the Gemfile and then bundle install
  `gem 'activerecord-deprecated_finders', require: 'active_record/deprecated_finders'`

- fix deprecated call to BasicObject, change "basic" to "proxy" in lines 1 and 5 of lib/redmine_better_gantt_chart/active_record/callback_extensions_for_rails3.rb

- fix "pourcent" to "percent" spelling errors in lib/redmine/helpers/better_gantt.rb 

- make sure plugin folder is named redmine_better_gantt_chart

**Comment by kulesa** [comment]
@jancybsec Thank you! Mind creating a pull request for this?

**Comment by jancybsec** [comment]
@kulesa all done!

**Comment by janekska** [comment]
It is working for me:

> Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.9.3
  Filesystem                     
Redmine plugins:
  event_notifications            3.2.1
  planner                        0.5
  redmine_checklists             3.1.5
  redmine_dashboard              2.7.1
  redmine_mail_reminder          3.0.0.0001
  redmine_mentions               0.0.1
  redmine_percent_done           1.0.0
  redmine_spent_time_in_issue_description 2.8.0
  redmine_tags                   3.1.1
  redmine_work_time              0.3.3
  timelog_timer                  2.0.0
