### ISSUE TITLE
500 error on project gantt page - Redmine 3.4 and later

### ISSUE THREAD

**Issue by adanielvv** [kulesa/redmine_better_gantt_chart#130]
link_to_content_update is deprecated

Exactly the same error as:
https://github.com/agileware-jp/redmine_work_days/issues/14

**Comment by NCookies** [comment]
I have same problem

```
Started GET "/redmine/issues/gantt" for 127.0.0.1 at 2018-05-28 20:49:08 +0900
Processing by GanttsController#show as HTML
  Current user: anonymous
  Rendered queries/_filters.html.erb (56.0ms)
DEPRECATION WARNING: Relation#all is deprecated. If you want to eager-load a relation, you can call #load (e.g. `Post.where(published: true).load`). If you want to get an array of records from a relation, you can call #to_a (e.g. `Post.where(published: true).to_a`). (called from projects at C:/Bitnami/redmine-3.4.5-0/apps/redmine/htdocs/plugins/redmine_better_gantt_chart/lib/redmine/helpers/better_gantt.rb:160)
  Rendered plugins/redmine_better_gantt_chart/app/views/gantts/show.html.erb within layouts/base (688.0ms)
Completed 500 Internal Server Error in 907ms (ActiveRecord: 86.0ms)

ActionView::Template::Error (undefined method `link_to_content_update' for #<#<Class:0x4818a38>:0x47d4ab8>
Did you mean?  link_to_function):
    308: <table style="width:100%">
    309: <tr>
    310:   <td align="left">
    311:     <%= link_to_content_update("\xc2\xab " + l(:label_previous),
    312:                                params.merge(@gantt.params_previous)) %>
    313:   </td>
    314:   <td align="right">
  plugins/redmine_better_gantt_chart/app/views/gantts/show.html.erb:311:in `_plugins_redmine_better_gantt_chart_app_views_gantts_show_html_erb___508228174_37404948'
  plugins/redmine_better_gantt_chart/lib/redmine_better_gantt_chart/gantts_controller_patch.rb:23:in `block (2 levels) in show_with_custom_helper'
  plugins/redmine_better_gantt_chart/lib/redmine_better_gantt_chart/gantts_controller_patch.rb:22:in `show_with_custom_helper'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
